spring:
  thymeleaf:
    cache: false
  redis:
    host: localhost
    port: 6379
  jackson:
    default-property-inclusion: non_null
  mvc:
    static-path-pattern: /static/**
    dispatch-options-request: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.3.137:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081
  servlet:
    context-path: /sell
logging:
#  config: classpath:/logbak-spring.xml
  level:
    com.imooc.sell.Data2Object.mapper: trace
wechat:
  # 公众账号, 授权
  mpAppId: wx150cec0373e2136a
#  mpAppId: wxd898fcb01713c658
  mpAppSecret: 0d5f3fd54b9bd492327725d6cd5e0b71

  # 开放平台,  卖家扫码登录用
  openAppId: wx150cec0373e2136a
  openAppSecret: 0d5f3fd54b9bd492327725d6cd5e0b71

  # 支付/商户号 借
#  mchId: 1483469312
  mchId: 1483469312
  mchKey: 098F6BCD4621D373CADE4E832627B4F6
  # 发起支付不需要证书, 退款需要
  keyPath: /Users/yd/githubproject/sell/doc/h5.p12
  notifyUrl: http://mango.nat100.top/sell/pay/notify
  templateId:
    orderStatus: aPSq5LuZrd1kF2K1eQYnzFEHsfhxObZNLVHyU2kvi08
project-url:
  wechatMpAuthorize: http://mango.nat100.top
  wechatOpenAuthorize: http://mango.nat100.top
  sell: /seller
  returnUrl: /buyer/order/list
