spring:
  redis:
    host: localhost
    port: 6379
  jackson:
    default-property-inclusion: non_null
  mvc:
    dispatch-options-request: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 65093270
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
server:
  port: 8081
  servlet:
    context-path: /sell
logging:
#  config: classpath:/logbak-spring.xml
  level:
    com.imooc.sell.Data2Object.mapper: trace
